# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 15:36
from __future__ import unicode_literals

from django.db import migrations

def wizard_builder_hack(apps,schema_editor):
    from wizard_builder.models import FormQuestion,QuestionPage
    QuestionPage = apps.get_model('wizard_builder',"questionpage")
    FormQuestion = apps.get_model('wizard_builder',"formquestion")
    if not (QuestionPage.objects.count() and FormQuestion.objects.count()):
        p=QuestionPage()
        p.save()
        f=FormQuestion(page=p)
        f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder','0001_initial')
    ]

    operations = [
        migrations.RunPython(wizard_builder_hack,lambda apps,schema_editor: None)
    ]
