# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 15:36
from __future__ import unicode_literals

from django.db import migrations

def wizard_builder_hack(apps,schema_editor):
    # this is a terrible hack to compensate for the fact that wizard builder can't load in the admin without
    # some objects in the database
    # Also, yes, I know I should be using apps.get_model(), but polymorphic has issues that way, I think because 
    # polymorphics custom save doen't work rith it
    from wizard_builder.models import FormQuestion,QuestionPage
    p=QuestionPage()
    p.save()
    f=FormQuestion(page=p)
    f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder','0001_initial')
    ]

    operations = [
        migrations.RunPython(wizard_builder_hack,lambda apps,schema_editor: None)
    ]
